name: Create-Random-Number-PR
on: workflow_dispatch
jobs:
  create-random-number-pr:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # missing .git if git version <= 2.14

      - name: Create commit
        run: |
          /home/vuongpd/Desktop/zigexn/zigexn-data/gh_api_test/actions-runner/echo_random.sh >> README.md

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          # token: ${{ secrets.GITHUB_TOKEN }} (default) or token: ${{ secrets.PAT }}
          commit-message: "Append new random number to README.md"
          committer: "Kuruma Runner <kuruma-runner-noreply@zigexn.vn>"
          author: "Kuruma Runner <kuruma-runner-noreply@zigexn.vn>"
          branch: "auto-created-pr/add-random-number-to-README"
          branch-suffix: timestamp
          base: main
          title: "[Auto Created PR] Add random number to README"
          body: |
            Update report:
            - Auto-generated by Kuruma Runner
            - Modify me in the .github/workflow/create_random_number_pr.yml
          labels: "main-auto-merge,delete-branch-after-closing"
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Repository Dispatch event type auto-merge-main-pr
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }} # Remember to setup REPO_ACCESS_TOKEN in actions/settings/secrets
          event-type: auto-merge-main-pr
