name: Delete-Branch-By-Ref
on:
  repository_dispatch:
    types: [main-is-auto-merged]
jobs:
  main-auto-merge:
    runs-on: self-hosted
    steps:
      - name: Get related PR information
        id: getpr
        run: |
          echo "::set-output name=pr-branch::$(curl -s https://api.github.com/repos/vuongpdz/gh_api_test/pulls/${{ github.event.client_payload.pr_number }} | jq '.head.ref' | sed 's/\"//g')"

      - name: Cleanup closed PR labeled delete-branch-after-closing
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ steps.getpr.outputs.pr-branch }}
