name: Delete-Branch-By-Ref
on:
  repository_dispatch:
    types: [main-is-auto-merged]
jobs:
  main-auto-merge:
    runs-on: self-hosted
    steps:
      - name: Get related PR information
        id: getpr
        run: |
          RELATED_PR_INFO=$(curl https://api.github.com/repos/vuongpdz/gh_api_test/pulls/${{ github.event.client_payload.pr_number }})
          echo "::set-output name=related-pr::$RELATED_PR_INFO"

      - name: Dump GitHub context
        run: |
          echo "${{ toJson(github) }}"
          echo "${{ fromJson(steps.getpr.outputs.related-pr) }}"
      # - name: Cleanup closed PR labeled delete-branch-after-closing
      #   uses: dawidd6/action-delete-branch@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branches: ${{ github.event.client_payload.ref }}
