name: Restart-MB6
on: workflow_dispatch
jobs:
  restart-mb6:
    runs-on: self-hosted
    steps:
      - name: Restart the application using Capistrano
        run: |
          /bin/bash -lc 'eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa_zigexn && cd /home/vuongpd/Desktop/zigexn/usedcar_v2 && bundle exec cap mobi6_vn deploy:restart'
          /bin/bash -lc 'eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa_zigexn && cd /home/vuongpd/Desktop/zigexn/usedcar_api && bundle exec cap mobi6_vn deploy:restart'

      - name: Sending Slack notification (lityourcode's general channel)
        run: |
          curl -X POST -H 'Content-Type: application/json' --data \
            '{"text": "<!channel> MB6 APP & API are restarted!"}' ${{ secrets.LITYOURCODE_GENERAL_SLACK_URL }}
