name: Test-CURL
on: workflow_dispatch
jobs:
  test-getting-pr-19-head-ref-using-curl:
    runs-on: self-hosted
    steps:
      - name: Get related PR information
        id: getpr
        run: |
          echo "::set-output name=pr-branch::$(curl -s https://api.github.com/repos/vuongpdz/gh_api_test/pulls/19 | jq '.head.ref' | sed 's/\"//g')"
      - name: Check outputs
        run: |
          echo "${{ steps.getpr.outputs.pr-branch }}"
